name: Run Tmate Script on Ubuntu

on:
  workflow_dispatch:  # Manual trigger

jobs:
  run-tmate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run Tmate Script
        run: python3 Workflow.py
